version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: local_password
      POSTGRES_DB: mono_bet_development
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: development
      DATABASE_PASSWORD: local_password
      DATABASE_NAME: mono_bet_development

volumes:
  db-data:
